# backend-api/backend-clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: backend-kvstore-access-binding
subjects:
  - kind: ServiceAccount
    name: backend-sa
    namespace: backend-api
roleRef:
  kind: ClusterRole
  name: backend-kvstore-access
  apiGroup: rbac.authorization.k8s.io