# backend-api/deployment.yaml (modified)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-backend
  namespace: backend-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi-backend
  template:
    metadata:
      labels:
        app: fastapi-backend
    spec:
      serviceAccountName: backend-sa # Add this line
      containers:
        - name: fastapi-backend
          image: localhost:5000/backend-image
          ports:
            - containerPort: 8000
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
            requests:
              memory: "128Mi"
              cpu: "250m"
          env:
            - name: MODE
              value: "prod"
            - name: KVSTORE_SERVICE
              value: kvstore-external #Add this environment variable