apiVersion: v1
kind: Service
metadata:
  name: fastapi-backend-service
  namespace: backend-api
spec:
  selector:
    app: fastapi-backend
  ports:
    - protocol: TCP
      port: 8000        # External port for backend service
      targetPort: 8000  # Internal port of the container
  type: ClusterIP       # Internal-only access
